### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by cosmoscalibur** [manuela98/Emergencias_911_#1]
# Ponderación
- `README.md`: 0,5/0,5
- Instalación: 0,2/0,3
- Inicialización: 0,1/0,3
- Consultas: 0,2/0,3
- Extracción: 1,5/1,5
- Descarga: 0,7/1,0
- Consulta: 0,3/0,5
- `LICENSE`: 0,2/0,2
- Markdown: 0,4/0,4

Ponderación: 4,1
# Retroalimentación
- `README.md`: La documentación no es para la implementación sino para el uso.
- Documentación:
  - Instalación: `numpy` es modulo externo que requiere ser instalado y no esta indicado en el proceso de instalación. `display` y `Markdown` son usados desde `IPython` y no son modulos separados, pero este último no esta indicado en la instalación. Los modulos `os` y `time` son del _core_ por lo cual no requieren ser especificados en sus dependencias y para el usuario final no le importa que esten siendo usados internamente.
  - Inicialización: No se usaron celdas de código que ilustran su inicialización. La redacción del punto 2 de la inicialización se había indicado la corrección y se presento sin modificación.  
  - Consultas: El funcionamiento del código debe ser independiente de los notebooks. Se indico que el notebook es solo para documentación por lo cual las indicaciones de uso no pueden depender de referenciar el mismo notebook.
- Código:
  - Extracción:
  - Descargas: El código de descarga parte de una configuración permanente del directorio de descarga del navegador, lo cual resulta erroneo o debe ser necesario aclararse en la documentación. Conviene más el uso de `requests.get` para la descarga del archivo de tal forma que no deban poner un tiempo de espera el cual realmente depende del estado de la red.  
  - Consulta: La consulta no es exclusiva en notebook, y debe poderse realizar por consola también. De esta forma, la consulta no es posible usarla para un análisis ya que no devuelve datos sino texto markdown el cual requiere nuevamente de eliminarle la componente de visualización para su análisis.
- `LICENSE`:
- Markdown:

**Comment by JosemaUdeM** [comment]
https://github.com/manuela98/Emergencias_911_/commit/339fd4ff36c17e192c854c4b97dd2c36d27ee6f2

**Comment by cosmoscalibur** [comment]
# Entrega 2

## Ponderación
- Instalación: 0,4/0,5  
- Estadistica Descriptiva: 1,2/1,2  
- Estadistica Inferencial: 0,0/1,5  
- Reporte Estadistico: 0,8/1,0  
- Correcciones Entrega 1: 0,7/0,8  

Ponderación: 3,5/5,0

## Retroalimentación
- Instalación:  No se encuentra actualización del proceso de instalación con base a las nuevas dependencias del proyecto en el archivo `README.md`.  
- Código:  
  - Estadistica descriptiva:  
  - Estadistica inferencial: Los promedios son descriptivos y no inferenciales. El notebook usa imagen estatica de markdown pero no subieron la imagen. Esta etapa dependía de reportes y no de gráficos.  
  - Reporte estadistico: Falta una visualización adecuada en formato markdown para el notebook.  
- Correcciones Entrega 1: 
  - Corrección realizada del `README`.  
  - Correcciones adecuadas de la documentación.  
  - Corrección adecuada de la obtención de los archivos sin depender de rutas absolutas.  
  - `nconsulta` no existe y es ejecutado en el notebook en lugar de `consulta`.

**Comment by cosmoscalibur** [comment]
Persisten problemas en las indicaciones de instalación de dependencias. Ponderación: 4,9/5,0.

**Comment by cosmoscalibur** [comment]
# Entrega 3

## Ponderación
- Instalación: 0,4/0,5  
- Visualización: 1,0/1,2  
- Estadistica inferencial: 0,4/0,8  
- Documentación: 0,3/0,5  
- Reporte final: 0,9/1,2  
- Correcciones Entrega 2: 0,4/0,8  
- Subtotal: 3,4  
- Reporte automático: /0,5  

## Retroalimentación
- Instalación: No se indica instalación de `jupyter`.  
- Código:  
  - Visualización: No hay consistencia de orden cronológico en la graficación frente a los elementos temporales asociados con nombres. Esto dificulta el análisis de los datos. Hay ausencia de titulo y de leyendas en algunos gráficos.  
  - Estadistica inferencial: Se presento como estadistica inferencial la sola generación de gráficos. Un gráfico sin las funciones usadas, o coeficientes o algún mecanismo que no sea visual no permite dar una cuantificación formal. Visualización y estadística son dos etapas separadas y no se nota la etapa de estadística inferencial más que por la visualización. Igualmente no hay ninguna mención ni muestra de ejecución de este bloque de código.  
- Documentación: La documentación no hace detalle sobre la ausencia de datos estadísticos asociados a la componente inferencial. Tampoco aclara la forma de consultar o diferenciar los gráficos generados, ya que al ilustrar los ejemplos no se dice nada de como fueron generados o el nombre con el cual fueron guardados ( y ante la ausencia de titulo en los gráficos esto hace imposible su buen uso).  
- Reporte final: Hay ausencia de pie de imagen en todas las figuras. Igualmente no hay presencia de bibliografía. No se hizo uso de sección de resumen (ambiente `abstract`) ni uso de referencias cruzadas `ref` (las figuras fueron llamadas manualmente).  
- Correciones Entrega 2: Omisión a las indicaciones realizadas en la presentación final y durante la feria de la física. Dichas correcciones no implicaban mayor tiempo.  
- Reporte automático:
